wheel1:
  pid:
    p: 1.0
    i: 0.1
    d: 0.01

wheel2:
  pid:
    p: 1.0
    i: 0.1
    d: 0.01

wheel3:
  pid:
    p: 1.0
    i: 0.1
    d: 0.01

wheel4:
  pid:
    p: 1.0
    i: 0.1
    d: 0.01

